import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const clean=(v:unknown,m=300)=>String(v??"").trim().slice(0,m);
const emailOk=(v:string)=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const now=()=>new Date().toISOString();
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function rawToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function earliest(a:string|null,b:string){if(!a)return b;return new Date(a)<new Date(b)?a:b}
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});

type Viewer={id:string;gallery_id:string;expires_at:string;share_link_id:string|null;download_unlocked_at:string|null};
async function viewer(t:string):Promise<Viewer|null>{if(!t||t.length<30)return null;const {data}=await sb.from("spodja_gallery_viewers").select("id,gallery_id,expires_at,share_link_id,download_unlocked_at").eq("session_token_hash",await hash(t)).gt("expires_at",now()).maybeSingle();if(!data)return null;await sb.from("spodja_gallery_viewers").update({last_seen_at:now()}).eq("id",data.id);return data as Viewer}
async function shareScope(v:Viewer){if(!v.share_link_id)return null;const {data}=await sb.from("spodja_gallery_share_links").select("asset_ids,expires_at,revoked_at").eq("id",v.share_link_id).maybeSingle();if(!data||data.revoked_at||(data.expires_at&&new Date(data.expires_at)<=new Date()))return [] as string[];return (data.asset_ids||[]) as string[]}
async function log(g:string,v:string|null,type:string,asset:string|null=null,meta:Record<string,unknown>={}){await sb.from("spodja_gallery_activity").insert({gallery_id:g,viewer_id:v,asset_id:asset,event_type:clean(type,60),metadata:meta})}

async function payload(gid:string,v?:Viewer|null){
  const {data:g,error}=await sb.from("spodja_galleries").select("id,slug,title,subtitle,service_type,client_name,event_date,status,requires_email,download_pin_hash,allow_downloads,allow_high_res,allow_shop,download_gate,payment_status,total_amount_cents,paid_amount_cents,balance_due_cents,balance_due_at,cover_asset_id,expires_at,watermark_previews,settings").eq("id",gid).single();
  if(error||!g)throw new Error("gallery_not_found");if(g.expires_at&&new Date(g.expires_at)<=new Date())throw new Error("gallery_expired");if(["draft","archived"].includes(g.status))throw new Error("gallery_unavailable");
  const scope=v?await shareScope(v):null;
  const {data:sets}=await sb.from("spodja_gallery_sets").select("id,slug,title,description,sort_order").eq("gallery_id",gid).order("sort_order");
  let q=sb.from("spodja_gallery_assets").select("id,set_id,title,alt_text,media_type,preview_url,storage_bucket,storage_path_web,width_px,height_px,sort_order,downloadable,is_cover,metadata").eq("gallery_id",gid).order("sort_order");
  if(scope!==null){if(!scope.length)return {gallery:{...g,download_pin_hash:undefined,download_pin_required:!!g.download_pin_hash},sets:[],assets:[],products:[],quick_share:true};q=q.in("id",scope)}
  const {data:raw}=await q;const assets=[] as any[];
  for(const a of raw||[]){let src=a.preview_url;if(!src&&a.storage_bucket&&a.storage_path_web){const {data}=await sb.storage.from(a.storage_bucket).createSignedUrl(a.storage_path_web,3600,{transform:{width:2400,quality:82}});src=data?.signedUrl||null}assets.push({id:a.id,set_id:a.set_id,title:a.title,alt_text:a.alt_text,media_type:a.media_type,src,width_px:a.width_px,height_px:a.height_px,sort_order:a.sort_order,downloadable:a.downloadable,is_cover:a.is_cover,metadata:a.metadata})}
  let products:any[]=[];if(g.allow_shop){const {data}=await sb.from("spodja_gallery_products").select("id,product_type,name,description,price_cents,metadata").eq("active",true).or(`gallery_id.eq.${gid},gallery_id.is.null`).order("created_at");products=data||[]}
  const safeGallery={...g,download_pin_hash:undefined,download_pin_required:!!g.download_pin_hash,download_unlocked:!!v?.download_unlocked_at};
  return {gallery:safeGallery,sets:sets||[],assets,products,quick_share:scope!==null}
}

async function access(b:any){const email=clean(b.email,180).toLowerCase(),name=clean(b.name,120)||null;if(!emailOk(email))return json({error:"invalid_email"},400);let g:any=null,share:any=null;if(b.share_token){const {data}=await sb.from("spodja_gallery_share_links").select("id,gallery_id,expires_at,revoked_at").eq("token_hash",await hash(clean(b.share_token,200))).maybeSingle();if(!data||data.revoked_at||(data.expires_at&&new Date(data.expires_at)<=new Date()))return json({error:"share_link_invalid"},404);share=data;const {data:gg}=await sb.from("spodja_galleries").select("*").eq("id",data.gallery_id).maybeSingle();g=gg}else{const code=clean(b.code,120).toUpperCase();if(!code)return json({error:"gallery_code_required"},400);const {data}=await sb.from("spodja_galleries").select("*").eq("access_code_hash",await hash(code)).maybeSingle();g=data}if(!g||["draft","archived"].includes(g.status))return json({error:"gallery_not_found"},404);if(g.expires_at&&new Date(g.expires_at)<=new Date())return json({error:"gallery_expired"},410);if(g.requires_email&&!email)return json({error:"email_required"},400);const t=rawToken(),exp=earliest(g.expires_at,new Date(Date.now()+30*86400000).toISOString());const {data:v,error}=await sb.from("spodja_gallery_viewers").insert({gallery_id:g.id,name,email:email||null,marketing_opt_in:!!b.marketing_opt_in,session_token_hash:await hash(t),share_link_id:share?.id||null,expires_at:exp}).select("id,gallery_id,expires_at,share_link_id,download_unlocked_at").single();if(error||!v)return json({error:"gallery_access_failed"},500);await log(g.id,v.id,share?"quick_share_open":"gallery_open",null,{email_registered:!!email});return json({ok:true,session_token:t,session_expires_at:exp,...await payload(g.id,v as Viewer)})}
async function bootstrap(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const {data:lists}=await sb.from("spodja_gallery_favorite_lists").select("id,name,purpose,submitted_at,spodja_gallery_favorites(asset_id,note)").eq("viewer_id",v.id).order("created_at");return json({ok:true,...await payload(v.gallery_id,v),favorite_lists:lists||[]})}
function purpose(n:string){n=n.toLowerCase();if(n.includes("album"))return "album";if(n.includes("print"))return "prints";if(n.includes("retouch"))return "retouch";if(n.includes("favorite"))return "favorites";return "custom"}
async function allowed(v:Viewer){const s=await shareScope(v);if(s!==null)return new Set(s);const {data}=await sb.from("spodja_gallery_assets").select("id").eq("gallery_id",v.gallery_id);return new Set((data||[]).map((x:any)=>x.id))}
async function syncLists(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const ls=Array.isArray(b.lists)?b.lists.slice(0,12):[],ok=await allowed(v);for(const input of ls){const name=clean(input.name,40);if(!name)continue;const {data:l}=await sb.from("spodja_gallery_favorite_lists").upsert({gallery_id:v.gallery_id,viewer_id:v.id,name,purpose:purpose(name)},{onConflict:"viewer_id,name"}).select("id").single();if(!l)continue;await sb.from("spodja_gallery_favorites").delete().eq("list_id",l.id);const items=(Array.isArray(input.items)?input.items:[]).slice(0,500).filter((x:any)=>ok.has(clean(x.asset_id,100))).map((x:any)=>({list_id:l.id,asset_id:clean(x.asset_id,100),note:clean(x.note,1200)||null}));if(items.length)await sb.from("spodja_gallery_favorites").insert(items)}await log(v.gallery_id,v.id,"favorites_sync",null,{list_count:ls.length});return json({ok:true})}
async function submitList(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const {data}=await sb.from("spodja_gallery_favorite_lists").update({submitted_at:now()}).eq("id",clean(b.list_id,80)).eq("viewer_id",v.id).select("id,name").maybeSingle();if(!data)return json({error:"list_not_found"},404);await log(v.gallery_id,v.id,"favorite_list_submitted",null,{list_id:data.id,name:data.name});return json({ok:true,submitted_at:now()})}
async function quickShare(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const ok=await allowed(v),ids=[...new Set((Array.isArray(b.asset_ids)?b.asset_ids:[]).map((x:any)=>clean(x,100)).filter((x:string)=>ok.has(x)))].slice(0,100);if(!ids.length)return json({error:"no_assets_selected"},400);const t=rawToken(),{data:g}=await sb.from("spodja_galleries").select("expires_at").eq("id",v.gallery_id).single(),exp=earliest(g?.expires_at||null,new Date(Date.now()+30*86400000).toISOString());const {error}=await sb.from("spodja_gallery_share_links").insert({gallery_id:v.gallery_id,created_by_viewer_id:v.id,token_hash:await hash(t),asset_ids:ids,label:clean(b.label,120)||null,expires_at:exp});if(error)return json({error:"share_create_failed"},500);await log(v.gallery_id,v.id,"quick_share_created",null,{count:ids.length});return json({ok:true,share_token:t,expires_at:exp})}
function canDownload(g:any){if(!g.allow_downloads)return false;if(g.download_gate==="always")return true;if(g.download_gate==="deposit_paid")return ["deposit_paid","paid_in_full","po_terms"].includes(g.payment_status);return ["paid_in_full","po_terms"].includes(g.payment_status)}
async function galleryForDownload(v:Viewer){const {data:g}=await sb.from("spodja_galleries").select("allow_downloads,allow_high_res,download_gate,payment_status,balance_due_cents,balance_due_at,download_pin_hash").eq("id",v.gallery_id).single();if(!g||!canDownload(g))return {error:json({error:"balance_gate",balance_due_cents:g?.balance_due_cents||0,balance_due_at:g?.balance_due_at||null},402)};if(g.download_pin_hash&&!v.download_unlocked_at)return {error:json({error:"download_pin_required"},403)};return {g}}
async function unlockDownload(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const {data:g}=await sb.from("spodja_galleries").select("download_pin_hash").eq("id",v.gallery_id).single();if(!g?.download_pin_hash){await sb.from("spodja_gallery_viewers").update({download_unlocked_at:now()}).eq("id",v.id);return json({ok:true})}const pin=clean(b.pin,32);if(!pin||await hash(pin)!==g.download_pin_hash){await log(v.gallery_id,v.id,"download_pin_failed");return json({error:"download_pin_invalid"},403)}await sb.from("spodja_gallery_viewers").update({download_unlocked_at:now()}).eq("id",v.id);await log(v.gallery_id,v.id,"download_pin_unlocked");return json({ok:true})}
async function signedFile(v:Viewer,id:string,quality:string){const ok=await allowed(v);if(!ok.has(id))throw new Error("asset_not_allowed");const {data:a}=await sb.from("spodja_gallery_assets").select("preview_url,storage_bucket,storage_path_web,storage_path_high,downloadable,title").eq("id",id).eq("gallery_id",v.gallery_id).maybeSingle();if(!a||!a.downloadable)throw new Error("download_disabled");const path=quality==="high"?(a.storage_path_high||a.storage_path_web):a.storage_path_web;let url=a.preview_url;if(a.storage_bucket&&path){const {data,error}=await sb.storage.from(a.storage_bucket).createSignedUrl(path,600,{download:clean(a.title,80)||undefined});if(error||!data?.signedUrl)throw new Error("download_url_failed");url=data.signedUrl}if(!url)throw new Error("file_not_ready");return {id,title:a.title||"Spodja photo",url,expires_in:a.storage_bucket?600:null}}
async function download(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const quality=clean(b.quality,20)==="high"?"high":"web",gate=await galleryForDownload(v);if(gate.error)return gate.error;if(quality==="high"&&!gate.g!.allow_high_res)return json({error:"high_res_disabled"},403);try{const f=await signedFile(v,clean(b.asset_id,100),quality);await log(v.gallery_id,v.id,"download",f.id,{quality});return json({ok:true,...f})}catch(e){return json({error:e instanceof Error?e.message:"download_failed"},403)}}
async function downloadBatch(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const quality=clean(b.quality,20)==="high"?"high":"web",gate=await galleryForDownload(v);if(gate.error)return gate.error;if(quality==="high"&&!gate.g!.allow_high_res)return json({error:"high_res_disabled"},403);const ids=[...new Set((Array.isArray(b.asset_ids)?b.asset_ids:[]).map((x:any)=>clean(x,100)).filter(Boolean))].slice(0,50),files=[] as any[];for(const id of ids){try{files.push(await signedFile(v,id,quality))}catch{}}if(!files.length)return json({error:"no_downloadable_assets"},404);await log(v.gallery_id,v.id,"download_batch",null,{quality,count:files.length});return json({ok:true,files,quality})}
async function couponFor(galleryId:string,code:string,subtotal:number){if(!code)return null;const h=await hash(code.toUpperCase());const {data}=await sb.from("spodja_gallery_coupons").select("id,discount_type,discount_value,max_redemptions,redeemed_count,starts_at,expires_at,active,label").eq("code_hash",h).eq("active",true).or(`gallery_id.eq.${galleryId},gallery_id.is.null`).limit(1).maybeSingle();if(!data)return null;const t=Date.now();if(data.starts_at&&new Date(data.starts_at).getTime()>t)return null;if(data.expires_at&&new Date(data.expires_at).getTime()<=t)return null;if(data.max_redemptions!=null&&data.redeemed_count>=data.max_redemptions)return null;const discount=data.discount_type==="percent"?Math.min(subtotal,Math.round(subtotal*Math.min(data.discount_value,100)/100)):Math.min(subtotal,data.discount_value);return {...data,discount}}
async function createOrder(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const raw=Array.isArray(b.items)?b.items.slice(0,100):[];const ids=[...new Set(raw.map((x:any)=>clean(x.product_id,100)).filter(Boolean))];if(!ids.length)return json({error:"order_empty"},400);const {data:products}=await sb.from("spodja_gallery_products").select("id,gallery_id,name,price_cents,active").in("id",ids).eq("active",true);const pm=new Map((products||[]).filter((p:any)=>!p.gallery_id||p.gallery_id===v.gallery_id).map((p:any)=>[p.id,p]));let subtotal=0;const items=[] as any[];for(const r of raw){const p:any=pm.get(clean(r.product_id,100));if(!p||p.price_cents==null)continue;const q=Math.max(1,Math.min(20,Number(r.quantity)||1));subtotal+=p.price_cents*q;items.push({product_id:p.id,asset_id:clean(r.asset_id,100)||null,description:p.name,quantity:q,unit_price_cents:p.price_cents})}if(!items.length)return json({error:"order_empty"},400);const c=await couponFor(v.gallery_id,clean(b.coupon,40),subtotal),discount=c?.discount||0,total=Math.max(0,subtotal-discount);const {data:o,error}=await sb.from("spodja_gallery_orders").insert({gallery_id:v.gallery_id,viewer_id:v.id,status:total>0?"pending_payment":"confirmed",total_cents:total,coupon_id:c?.id||null,discount_cents:discount,notes:clean(b.notes,1200)||null}).select("id,order_ref,status,total_cents,discount_cents").single();if(error||!o)return json({error:"order_create_failed"},500);await sb.from("spodja_gallery_order_items").insert(items.map(i=>({...i,order_id:o.id})));if(c)await sb.from("spodja_gallery_coupons").update({redeemed_count:c.redeemed_count+1}).eq("id",c.id).eq("redeemed_count",c.redeemed_count);await log(v.gallery_id,v.id,"order_created",null,{order_ref:o.order_ref,item_count:items.length,total_cents:total,discount_cents:discount});return json({ok:true,...o,subtotal_cents:subtotal,coupon_label:c?.label||null})}
async function activity(b:any){const v=await viewer(clean(b.session_token,300));if(!v)return json({error:"session_invalid"},401);const type=clean(b.event_type,60),id=clean(b.asset_id,100)||null;if(!type)return json({error:"event_type_required"},400);if(id&&!(await allowed(v)).has(id))return json({error:"asset_not_allowed"},403);await log(v.gallery_id,v.id,type,id,b.metadata&&typeof b.metadata==="object"?b.metadata:{});return json({ok:true})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const b=await req.json(),a=clean(b.action,40);if(a==="access")return await access(b);if(a==="bootstrap")return await bootstrap(b);if(a==="sync_lists")return await syncLists(b);if(a==="submit_list")return await submitList(b);if(a==="quick_share")return await quickShare(b);if(a==="unlock_download")return await unlockDownload(b);if(a==="download")return await download(b);if(a==="download_batch")return await downloadBatch(b);if(a==="create_order")return await createOrder(b);if(a==="activity")return await activity(b);return json({error:"unknown_action"},400)}catch(e){console.error(e);const m=e instanceof Error?e.message:"gallery_api_failed";if(m==="gallery_expired")return json({error:m},410);if(["gallery_not_found","gallery_unavailable"].includes(m))return json({error:m},404);return json({error:"gallery_api_failed"},500)}});
